### ISSUE TITLE
Trying to send a variable to the less file but it doesn't seem to be converting correctly

### ISSUE THREAD

**Issue by jmsobe** [BernhardBaumrock/RockLESS#1]
This is my code that I am using

$less = $modules->get('RockLESS');
$less->vars = [
  'primarycolor' => $site_navbar_color,
];
$css = $less->getCSS($config->paths->templates . 'less/theme.less')->cssUrl;
echo "<link rel='stylesheet' type='text/css' href='$css'>";
 
Any thoughts

**Comment by BernhardBaumrock** [comment]
Maybe you just need to trigger the regeneration by deleting the CSS file?

You can setup automatic monitoring of files like this:
```php
    // get list of files to monitor
    $monitor = $this->files->find(__DIR__, ['extensions'=>['less']]);
    $monitor = array_merge($monitor, $this->files->find(
      $this->config->paths->assets."RockSkinUikit",
      ['extensions' => ['less']]
    ));
    $monitor[] = $this->config->paths->site . "config.php";

    // load less module
    /** @var RockLESS $less */
    $less = $this->modules->get('RockLESS');
    $less->vars = $this->config->lessVars;
    $newfile = "$file.css";
    $less->getCSS($file, $newfile, null, null, $monitor);
```

**Comment by jmsobe** [comment]
Thanks Bernhard it looks its compiling but instead of the hex color color code I'm getting this in the compiled CSS file


a {
  color: 193 AB1;
}

**Comment by jmsobe** [comment]
I just figured it out. I was using the color picker field type in pW which apparently doesn't send a "#" sign. If I concatenate the "#" sign with the variable it works. Thanks again for this great module
